version: "3.9"

services:
  tgdd-db:
    image: postgres:15
    container_name: tgdd-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - tgdd_data:/var/lib/postgresql/data

  tgdd-backend:
    build: .
    container_name: tgdd-backend
    restart: always
    depends_on:
      - tgdd-db
    ports:
      - "5050:${PORT}"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

volumes:
  tgdd_data:
